Repository nostalgic-css/NES.css, pull requests merged in 2018-12, with the labels that each got.

#45 shrinking pixels only @ FF
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/utilities/icon-mixin.scss
Labels: improvement

#47 Adds trophy css icon (same colors as star icon
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  index.html
  scss/icons/icons.scss
  scss/icons/trophy.scss
Labels: enhancement

#49 Add Recommended fonts list
  README-jp.md
  README.md
Labels: document

#43 Updating snes-icon to have a lighter color for the top buttons.
  scss/pixel-arts/snes-icon.scss
Labels: improvement

#52 swapped primary and success button styling
  css/nes.css
  scss/elements/buttons.scss
Labels: improvement

#55 Add empty state icons
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  index.html
  scss/icons/heart.scss
  scss/icons/icons.scss
  scss/icons/like.scss
  scss/icons/star.scss
Labels: enhancement

#56 Update input success color for both css and sass
  css/nes.css
  scss/form/inputs.scss
Labels: improvement

#61 Fix title in container
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/elements/containers.scss
Labels: bug

#63 fix .is-center and .is-right
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/elements/containers.scss
Labels: bug

#66 Added youtube icon and an example in the docs
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  index.html
  scss/icons/icons.scss
  scss/icons/youtube.scss
Labels: enhancement

#50 Set up Commitizen, CircleCI, and `semantic-release`
  .circleci/config.yml
  README.md
  commitlint.config.js
  css/nes.min.css
  package-lock.json
  package.json
Labels: improvement

#71 Add Storybook
  .storybook/addons.js
  .storybook/config.js
  README.md
  docs/balloons.stories.js
  docs/buttons.stories.js
  docs/containers.stories.js
  docs/icons.stories.js
  docs/inputs.stories.js
  docs/table.stories.js
  package.json
Labels: improvement

#80 Fix config files
  .gitignore
  .storybook/addons.js
  .storybook/config.js
  commitlint.config.js
  package-lock.json
  package.json
Labels: bug

#48 feat(breaking): remove google font import
  .storybook/preview-head.html
  README-jp.md
  README.md
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  index.html
  scss/base/variables.scss
Labels: breaking, waiting

#84 feat(button): add disabled state button
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  docs/buttons.stories.js
  index.html
  package-lock.json
  scss/elements/buttons.scss
Labels: enhancement

#88 Update repo links
  README-jp.md
  README.md
  package.json
Labels: devops

#90 Issue and Pull Request templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: document

#14 🐁 add cursor
  assets/cursor-click.png
  assets/cursor.png
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/base/generic.scss
  scss/base/variables.scss
  scss/elements/buttons.scss
  scss/elements/checkboxes.scss
  scss/elements/radios.scss
Labels: enhancement

#100 fix(table): added margin 4px to table is-bordered class
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/elements/tables.scss
Labels: bug

#78 feat: add table is-dark class similar to the container
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  docs/table.stories.js
  index.html
  scss/elements/tables.scss
Labels: enhancement

#103 Fix alignment without title
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/elements/containers.scss
Labels: bug

#106 Fix title position when use is-rounded
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/elements/containers.scss
Labels: bug

#96 feat: added google icon
  docs/icons.stories.js
  index.html
  scss/elements/buttons.scss
  scss/icons/google.scss
  scss/icons/icons.scss
Labels: enhancement

#44 Fix stray pixels on focused inputs such as checkboxes and radios
  scss/base/generic.scss
Labels: improvement

#114 feat(table): add table is-dark is-bordered in index.html
  index.html
Labels: bug

#111 storybook container is-dark font color
  .storybook/config.js
  index.html
  scss/elements/containers.scss
Labels: bug

#118 fix: preserve outline0 for checkboxes and radios only
  scss/base/generic.scss
Labels: bug

#67 add medium icon set
  index.html
  scss/icons/icons.scss
  scss/icons/medium.scss
Labels: enhancement, waiting

#68 add twitch icon
  index.html
  scss/icons/icons.scss
  scss/icons/twitch.scss
Labels: enhancement, waiting

#69 add reddit icon
  index.html
  scss/icons/icons.scss
  scss/icons/reddit.scss
Labels: enhancement, waiting

#120 fix(inputs.scss): fix field responsive
  scss/form/inputs.scss
Labels: bug

#135 Update inputs.scss
  scss/form/inputs.scss
Labels: improvement

#134 fix(balloon.scss): fix gaps in balloon
  scss/elements/balloons.scss
Labels: bug

#122 feat(icons): add whatsapp icon
  docs/icons.stories.js
  index.html
  scss/icons/icons.scss
  scss/icons/whatsapp.scss
Labels: waiting

#132 refactor: color variables
  scss/base/variables.scss
  scss/elements/buttons.scss
  scss/elements/checkboxes.scss
  scss/elements/containers.scss
  scss/elements/radios.scss
  scss/form/inputs.scss
Labels: improvement

#141 fix(buttons.scss): fix btn border
  scss/elements/buttons.scss
Labels: bug

#142 feat(textarea): add textarea component
  docs/textarea.stories.js
  index.html
  scss/form/inputs.scss
Labels: enhancement

#133 fix(tables.scss): add margin to table is-border class
  index.html
  scss/elements/tables.scss
  style.css
Labels: bug

#136 fix(containers.scss): fix alignment of title
  scss/elements/containers.scss
Labels: bug

#149 fix(icons): changed pokemons icons width and height
  scss/pixel-arts/bulbasaur.scss
  scss/pixel-arts/charmander.scss
  scss/pixel-arts/squirtle.scss
Labels: bug

#140 Add progress bar
  docs/progress.stories.js
  index.html
  scss/elements/_index.scss
  scss/elements/progress.scss
Labels: enhancement

#82 (breaking changes)Add prefix to class name
  docs/balloons.stories.js
  docs/buttons.stories.js
  docs/containers.stories.js
  docs/icons.stories.js
  docs/inputs.stories.js
  docs/table.stories.js
  docs/textarea.stories.js
  index.html
  scss/elements/balloons.scss
  scss/elements/buttons.scss
  scss/elements/checkboxes.scss
  scss/elements/containers.scss
  scss/elements/radios.scss
  scss/elements/tables.scss
  scss/form/inputs.scss
  scss/icons/icons.scss
  scss/pixel-arts/ash.scss
  scss/pixel-arts/bcrikko.scss
  scss/pixel-arts/bulbasaur.scss
  scss/pixel-arts/charmander.scss
  scss/pixel-arts/mario.scss
  scss/pixel-arts/octocat.scss
  scss/pixel-arts/phone.scss
  scss/pixel-arts/pokeball.scss
  scss/pixel-arts/smartphone.scss
  scss/pixel-arts/squirtle.scss
  style.css
Labels: breaking, enhancement

#156 feat(avatars): add avatar component
  docs/avatars.stories.js
  index.html
  scss/elements/_index.scss
  scss/elements/avatar.scss
Labels: enhancement

#151 feat(icons): add kirby icon
  docs/icons.stories.js
  index.html
  scss/pixel-arts/_index.scss
  scss/pixel-arts/ash.scss
  scss/pixel-arts/kirby.scss
  scss/pixel-arts/mario.scss
Labels: enhancement

#155 fix(style.css): fix margin and padding of body
  style.css
Labels: bug

#143 refactor: box shadow color
  scss/elements/balloons.scss
  scss/elements/containers.scss
  scss/utilities/icon-mixin.scss
Labels: enhancement

#150 feat: add favicon.ico
  favicon.ico
  index.html
Labels: enhancement

#157 Fix `develop` builds
  .circleci/config.yml
  package-lock.json
  package.json
Labels: devops

#167 Slim down our npm package
  .npmignore
Labels: devops, enhancement

#165 Add hot reloading to storybook
  .storybook/config.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
Labels: devops, enhancement

#174 docs(templates): split issue_template into two and change font size
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#176 Add icons linkedin and gmail
  docs/icons.stories.js
  index.html
  scss/icons/gmail.scss
  scss/icons/icons.scss
  scss/icons/linkedin.scss
Labels: enhancement

#182 UL lists
  docs/lists.stories.js
  index.html
  package-lock.json
  scss/elements/_index.scss
  scss/elements/lists.scss
Labels: enhancement

#171 Adds support for HTML dialog object
  docs/dialogs.stories.js
  scss/elements/dialogs.scss
Labels: enhancement

#183 add font recommendation for Korean in README.md
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  README.md
Labels: documentation, enhancement

#172 158 cursor url
  scss/base/variables.scss
Labels: bug, discussion

#181 Change is-center container class to is-centered
  docs/containers.stories.js
  index.html
  scss/elements/containers.scss
Labels: breaking, enhancement

#164 [#137] Update docs
  .github/CODE_OF_CONDUCT-es.md
  .github/CODE_OF_CONDUCT-jp.md
  .github/CODE_OF_CONDUCT-pt-BR.md
  .github/CONTRIBUTING-es.md
  .github/CONTRIBUTING-jp.md
  .github/CONTRIBUTING-pt-BR.md
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README-es.md
  README-jp.md
  README-pt-BR.md
  README.md
Labels: documentation, enhancement

#163 feat(tables): it replicates the responsive tables from bootstrap
  index.html
  scss/elements/tables.scss
  style.css
Labels: enhancement

#190 Sketch file added
  favicon.ico
  favicon.png
  index.html
  sketch/NES-css-index.sketch
Labels: documentation, waiting

#191 Autoupdate version
  package-lock.json
  package.json
  scripts/getBuildData.js
  scripts/scssFunctions.js
  scripts/updatePackageHeader.js
  scss/nes.scss
Labels: devops, enhancement

#198 [#196] use https instead of http
  index.html
Labels: bug

#199 [#197] Change source url
  index.html
Labels: bug

#201 fix: Ignore `commitlint` when merging to `master`
  .circleci/config.yml
Labels: bug

#203 fix: Fix the script that's run by `semantic-release`
  package.json
Labels: bug, devops

#204 🚀Release (Take 3!)
  package.json
Labels: release

#209 perf: Speed up pre-commit hooks
  package.json
Labels: enhancement

#210 Fix: mario icon on index.html and one line indent
  index.html
  scss/pixel-arts/_index.scss
Labels: enhancement

#213 Fix contributing links in all of the readmes
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
Labels: bug, documentation

#208 fix(dialog): Fix dialog corners
  docs/dialogs.stories.js
  scss/elements/_index.scss
  scss/elements/dialogs.scss
Labels: bug

#215 perf: icon shadow optimization
  scss/elements/checkboxes.scss
  scss/elements/lists.scss
  scss/elements/radios.scss
  scss/icons/icons.scss
  scss/pixel-arts/ash.scss
  scss/pixel-arts/bcrikko.scss
  scss/pixel-arts/bulbasaur.scss
  scss/pixel-arts/charmander.scss
  scss/pixel-arts/kirby.scss
  scss/pixel-arts/mario.scss
  scss/pixel-arts/nes-icon.scss
  scss/pixel-arts/nes-jp-icon.scss
  scss/pixel-arts/octocat.scss
  scss/pixel-arts/phone.scss
  scss/pixel-arts/pokeball.scss
  scss/pixel-arts/smartphone.scss
  scss/pixel-arts/snes-icon.scss
  scss/pixel-arts/snes-jp-icon.scss
  scss/pixel-arts/squirtle.scss
  scss/utilities/icon-mixin.scss
Labels: enhancement

#217 Styles for the <select /> element
  docs/select.stories.js
  index.html
  scss/form/_index.scss
  scss/form/selects.scss
  style.css
Labels: enhancement, waiting

#225 Add Chinese translation for REAME.md, CODE_OF_CONDUCT.md and CONTRIBUTING.md
  .github/CODE_OF_CONDUCT-es.md
  .github/CODE_OF_CONDUCT-jp.md
  .github/CODE_OF_CONDUCT-pt-BR.md
  .github/CODE_OF_CONDUCT-zh-CN.md
  .github/CONTRIBUTING-es.md
  .github/CONTRIBUTING-jp.md
  .github/CONTRIBUTING-pt-BR.md
  .github/CONTRIBUTING-zh-CN.md
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation, translations

#221 Change new-issue link in CONTRIBUTING.md
  .github/CONTRIBUTING-es.md
  .github/CONTRIBUTING-jp.md
  .github/CONTRIBUTING-pt-BR.md
  .github/CONTRIBUTING-zh-CN.md
  CONTRIBUTING.md
Labels: documentation, waiting

#231 Add Storybook backgrounds
  .storybook/addons.js
  .storybook/config.js
  .storybook/preview-head.html
  package-lock.json
  package.json
Labels: documentation, enhancement

#233 feat(text colors): adds text colors classes like is-primary etc.
  docs/text.stories.js
  scss/elements/_index.scss
  scss/elements/text.scss
Labels: enhancement

#224 Add components dir and split css file
  .github/CODE_OF_CONDUCT-es.md
  .github/CODE_OF_CONDUCT-jp.md
  .github/CODE_OF_CONDUCT-pt-BR.md
  .github/CONTRIBUTING-es.md
  .github/CONTRIBUTING-jp.md
  .github/CONTRIBUTING-pt-BR.md
  .github/CONTRIBUTING-zh-CN.md
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
  scripts/updatePackageHeader.js
  scss/components/_index.scss
  scss/nes-core.scss
  scss/nes.scss
Labels: devops, documentation

#216 Add badges component
  docs/badge.stories.js
  scss/elements/_index.scss
  scss/elements/badges.scss
Labels: enhancement, waiting
