Repository nostalgic-css/NES.css, pull requests merged in 2018-11, with the labels that each got.

#10 Accessibility: focus時のoutlineの調整
  README.md
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  index.html
  scss/elements/checkboxes.scss
  scss/elements/radios.scss
  scss/form/inputs.scss
Labels: improvement

#17 Update radios.scss
  scss/elements/radios.scss
Labels: improvement

#16 Update checkboxes.scss
  scss/elements/checkboxes.scss
Labels: improvement

#29 Prevents Overflowing Inputs
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  scss/form/inputs.scss
Labels: bug

#26 fix double semi-colon generated in css file
  css/nes.css
  scss/utilities/icon-mixin.scss
Labels: bug

#40 disable font-smoothing
  scss/base/generic.scss
Labels: improvement

#30 update label instances
  index.html
Labels: improvement

#41 Add table design
  css/nes.css
  css/nes.css.map
  css/nes.min.css
  index.html
  package-lock.json
  scss/elements/_index.scss
  scss/elements/tables.scss
Labels: enhancement
