Repository nostalgic-css/NES.css, pull requests merged in 2019-12, with the labels that each got.

#382 docs(baloons): added `is-dark` baloons to the docs
  docs/script.js
Labels: documentation

#383 docs: update contributors array
  docs/script.js
Labels: documentation

#385 refactor(storybook): storybook enhancement and cleanup
  package-lock.json
  package.json
  story/_helpers/icons.js
  story/_helpers/shared.js
  story/avatars.stories.js
  story/avatars/avatars.stories.js
  story/avatars/avatars.template.js
  story/badge.stories.js
  story/badge/badge.stories.js
  story/badge/badge.template.js
  story/balloons.stories.js
  story/balloons/balloons.stories.js
  story/balloons/balloons.template.js
  story/buttons.stories.js
  story/buttons/buttons.stories.js
  story/buttons/buttons.template.js
  story/containers.stories.js
  story/containers/containers.stories.js
  story/containers/containers.template.js
  story/dialogs.stories.js
  story/dialogs/dialogs.stories.js
  story/dialogs/dialogs.template.js
  story/icons.stories.js
  story/icons/icons.stories.js
  story/icons/icons.template.js
  story/icons/sprites.template.js
  story/inputs.stories.js
  story/inputs/checkboxes.template.js
  story/inputs/input.template.js
  story/inputs/inputs.stories.js
  story/inputs/radio.template.js
  story/lists.stories.js
  story/lists/lists.stories.js
  story/lists/lists.template.js
  story/progress.stories.js
  story/progress/progress.stories.js
  story/progress/progress.template.js
  story/select.stories.js
  story/select/select.stories.js
  story/select/select.template.js
  story/table.stories.js
  story/table/table.stories.js
  story/table/table.template.js
  story/text.stories.js
  story/text/text.stories.js
  story/text/text.template.js
  story/textarea.stories.js
  story/textarea/textarea.stories.js
  story/textarea/textarea.template.js
Labels: enhancement

#389 feat(heart): added new heart reaction state
  docs/script.js
  scss/icons/heart.scss
  scss/icons/icons.scss
  story/_helpers/icons.js
  story/icons/icons.stories.js
  story/icons/reactions.template.js
Labels: enhancement

#390 Update the document v2.3.0
  docs/index.html
  docs/script.js
Labels: documentation

#391 Release v2.3.0 (release note)
  docs/index.html
  docs/script.js
Labels: release

#393 fix(select): fixed select state styling
  scss/form/selects.scss
  story/select/select.template.js
Labels: bug, waiting - contributor
