Repository nostalgic-css/NES.css, pull requests merged in 2019-07, with the labels that each got.

#350 Fix radio and checkbox style in ios
  scss/form/checkboxes.scss
  scss/form/radios.scss
Labels: bug

#352 Fix focus color of buttons
  docs/script.js
  scss/elements/buttons.scss
Labels: bug

#351 Refactor visually hidden elements
  scss/elements/buttons.scss
  scss/form/checkboxes.scss
  scss/form/radios.scss
  scss/utilities/_index.scss
  scss/utilities/visually-hidden.scss
Labels: enhancement

#355 docs: add russian docs translation
  .github/CONTRUBUTING-ru.md
  .github/README-ru.md
  CONTRIBUTING.md
  README.md
Labels: documentation, translations, waiting - reviewer
