Repository nostalgic-css/NES.css, pull requests merged in 2019-10, with the labels that each got.

#364 String interpolation to calculate width of inputs. Fix #322
  .gitignore
  scss/form/inputs.scss
  scss/form/selects.scss
Labels: bug, waiting - reviewer

#366 feat(component-balloons): Dark Mode - Balloons
  scss/elements/balloons.scss
  story/balloons.stories.js
Labels: enhancement

#367 UPT: add LTS version for node engine
  package.json
Labels: enhancement

#363 docs: storybook install and demo
  README.md
  assets/storybook-demo.gif
Labels: documentation

#368 Fix stylelint errors
  package.json
  scss/elements/balloons.scss
  scss/form/inputs.scss
  scss/form/selects.scss
Labels: enhancement

#369 Update CONTORIBUTING.md
  .github/CONTRIBUTING-es.md
  .github/CONTRIBUTING-jp.md
  .github/CONTRIBUTING-pt-BR.md
  .github/CONTRIBUTING-zh-CN.md
  .github/CONTRUBUTING-ru.md
  CONTRIBUTING.md
  README.md
  assets/storybook-demo.gif
Labels: documentation

#370 Update icon-mixin.scss
  scss/utilities/icon-mixin.scss
Labels: enhancement

#372 Add input-file feature
  docs/script.js
  scss/elements/buttons.scss
Labels: enhancement

#373 feat(buttons): add storybook for input type file
  story/buttons.stories.js
Labels: enhancement

#371 Refactor fill-gaps
  scss/pixel-arts/ash.scss
  scss/pixel-arts/bcrikko.scss
  scss/pixel-arts/bulbasaur.scss
  scss/pixel-arts/charmander.scss
  scss/pixel-arts/kirby.scss
  scss/pixel-arts/mario.scss
  scss/pixel-arts/nes-icon.scss
  scss/pixel-arts/nes-jp-icon.scss
  scss/pixel-arts/octocat.scss
  scss/pixel-arts/phone.scss
  scss/pixel-arts/pokeball.scss
  scss/pixel-arts/smartphone.scss
  scss/pixel-arts/snes-icon.scss
  scss/pixel-arts/snes-jp-icon.scss
  scss/pixel-arts/squirtle.scss
  scss/utilities/_index.scss
  scss/utilities/fill-gaps.scss
  scss/utilities/icon-mixin.scss
Labels: enhancement
