Repository nostalgic-css/NES.css, pull requests merged in 2019-02, with the labels that each got.

#270 docs(readme): Fix link to misaki font
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
Labels: documentation, enhancement

#264 Fix pixelize bug
  scss/base/variables.scss
  scss/elements/lists.scss
  scss/form/checkboxes.scss
  scss/form/radios.scss
  scss/form/selects.scss
  scss/icons/icons.scss
  scss/pixel-arts/ash.scss
  scss/pixel-arts/bcrikko.scss
  scss/pixel-arts/bulbasaur.scss
  scss/pixel-arts/charmander.scss
  scss/pixel-arts/kirby.scss
  scss/pixel-arts/mario.scss
  scss/pixel-arts/nes-icon.scss
  scss/pixel-arts/nes-jp-icon.scss
  scss/pixel-arts/octocat.scss
  scss/pixel-arts/phone.scss
  scss/pixel-arts/pokeball.scss
  scss/pixel-arts/smartphone.scss
  scss/pixel-arts/snes-icon.scss
  scss/pixel-arts/snes-jp-icon.scss
  scss/pixel-arts/squirtle.scss
  scss/utilities/icon-mixin.scss
Labels: bug

#271 fix border bugs on chrome
  scss/form/inputs.scss
  scss/utilities/rounded-corners-mixin.scss
Labels: bug

#263 [#255] Dark mode for checkbox
  docs/inputs.stories.js
  scss/form/checkboxes.scss
Labels: enhancement, waiting

#266 refactor(cursors): Use data-uris for cursors
  .storybook/webpack.config.js
  package-lock.json
  package.json
  scss/base/variables.scss
Labels: enhancement, waiting

#275 fix(icons): removed two last empty lines from pokeball.
  scss/pixel-arts/pokeball.scss
Labels: enhancement

#272 Add show/hide code inside the index.html (docs)
  .prettierignore
  demo/lib/highlight-theme.css
  demo/lib/highlight.js
  demo/style.css
  index.html
  package.json
Labels: documentation, enhancement

#277 feat(index.html): changed img from gravatar to 8bit avatar. add alt.
  docs/avatars.stories.js
  index.html
Labels: documentation, enhancement

#279 feat(text): added is-disabled to text. changed text to texts.
  docs/select.stories.js
  docs/text.stories.js
  scss/elements/text.scss
Labels: enhancement

#280 fix(dialog): fix dialogs is-dark white border missing.
  scss/elements/dialogs.scss
Labels: bug

#283 Feat/add coin icon
  docs/icons.stories.js
  index.html
  scss/icons/coin.scss
  scss/icons/icons.scss
Labels: enhancement

#258 feat(icons): add psone controller icon
  docs/icons.stories.js
  index.html
  scss/pixel-arts/_index.scss
  scss/pixel-arts/psone.scss
Labels: enhancement

#278 feat(index.html): add dialogs/texts to index. changed table to tables
  demo/lib/dialog-polyfill.js
  demo/style.css
  dialog-polyfill.css
  index.html
  scss/elements/dialogs.scss
Labels: documentation, enhancement

#288 feat: make all variables default
  scss/base/variables.scss
Labels: enhancement

#289 Update version
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
Labels: documentation

#291 Change to latest version url
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
  index.html
Labels: documentation

#290 Release 2.0.0 (take two).
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
  index.html
Labels: release

#287 Fix cursor hand
  scss/base/variables.scss
Labels: enhancement

#296 Feat/add instagram icon
  .gitignore
  docs/icons.stories.js
  index.html
  package.json
  scss/icons/icons.scss
  scss/icons/instagram.scss
Labels: enhancement

#300 Fix a Chinese typo
  .github/README-zh-CN.md
Labels: documentation

#302 fix(icon-mixin.scss): fix style on firefox
  scss/utilities/icon-mixin.scss
Labels: bug

#303 [#301] Fix blurred borders in safari
  scss/utilities/rounded-corners-mixin.scss
Labels: bug

#292 Renew demo site
  .storybook/config.js
  demo/lib/dialog-polyfill.js
  demo/lib/highlight-theme.css
  demo/lib/highlight.js
  demo/style.css
  dialog-polyfill.css
  docs/favicon.png
  docs/index.html
  docs/lib/dialog-polyfill.css
  docs/lib/dialog-polyfill.js
  docs/lib/highlight-theme.css
  docs/lib/highlight.js
  docs/lib/vue.min.js
  docs/script.js
  docs/style.css
  index.html
  package.json
  story/avatars.stories.js
  story/badge.stories.js
  story/balloons.stories.js
  story/buttons.stories.js
  story/containers.stories.js
  story/dialogs.stories.js
  story/icons.stories.js
  story/inputs.stories.js
  story/lists.stories.js
  story/progress.stories.js
  story/select.stories.js
  story/table.stories.js
  story/text.stories.js
  story/textarea.stories.js
Labels: documentation

#308 feat(radio): add is-dark to radio
  docs/script.js
  scss/form/radios.scss
  story/inputs.stories.js
Labels: enhancement

#307 Grammar and misc fixes to README
  README.md
Labels: documentation, enhancement

#309 docs: fetch contributors
  docs/script.js
  docs/style.css
Labels: documentation

#305 Release!!
  .github/README-zh-CN.md
  .gitignore
  .storybook/config.js
  README.md
  demo/lib/dialog-polyfill.js
  demo/lib/highlight-theme.css
  demo/lib/highlight.js
  demo/style.css
  dialog-polyfill.css
  docs/favicon.png
  docs/index.html
  docs/lib/dialog-polyfill.css
  docs/lib/dialog-polyfill.js
  docs/lib/highlight-theme.css
  docs/lib/highlight.js
  docs/lib/vue.min.js
  docs/script.js
  docs/style.css
  index.html
  package.json
  scss/base/variables.scss
  scss/form/radios.scss
  scss/icons/icons.scss
  scss/icons/instagram.scss
  scss/utilities/icon-mixin.scss
  scss/utilities/rounded-corners-mixin.scss
  story/avatars.stories.js
  story/badge.stories.js
  story/balloons.stories.js
  story/buttons.stories.js
  story/containers.stories.js
  story/dialogs.stories.js
  story/icons.stories.js
  story/inputs.stories.js
  story/lists.stories.js
  story/progress.stories.js
  story/select.stories.js
  story/table.stories.js
  story/text.stories.js
  story/textarea.stories.js
Labels: release

#311 docs(readme.md): update latest version
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
Labels: documentation

#312 Release v2.1.0
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
Labels: release

#313 docs: fix github api
  docs/script.js
Labels: documentation

#314 Release v2.1.0 (Take 2)
  docs/script.js
Labels: release
