Repository nostalgic-css/NES.css, pull requests merged in 2019-03, with the labels that each got.

#321 chore(storybook): update storybook to version 5
  .storybook/config.js
  package-lock.json
  package.json
Labels: enhancement

#319 fix: fix borders bugs on chrome without breaking in firefox
  scss/utilities/rounded-corners-mixin.scss
Labels: bug

#325 Release v2.1.x
  .storybook/config.js
  package-lock.json
  package.json
  scss/utilities/rounded-corners-mixin.scss
Labels: release

#330 fix: remove underline in hover and set color
  scss/elements/buttons.scss
Labels: bug

#329 fix: remove input shadow on ios
  scss/form/inputs.scss
Labels: enhancement
