Repository nostalgic-css/NES.css, pull requests merged in 2019-06, with the labels that each got.

#342 feat: add the new nes-cursor class
  scss/helpers/_index.scss
  scss/helpers/pointer.scss
  scss/nes.scss
Labels: enhancement

#337 refactor: convert local images to data URIs
  .storybook/webpack.config.js
  package.json
  scripts/getFileAsDataURI.js
  scripts/scssFunctions.js
  scss/base/variables.scss
Labels: bug

#343 docs: add select and input is-dark to docs
  docs/script.js
Labels: documentation, enhancement

#341 Release v2.x 🚀
  .storybook/webpack.config.js
  docs/script.js
  package-lock.json
  package.json
  scripts/getFileAsDataURI.js
  scripts/scssFunctions.js
  scss/base/variables.scss
  scss/elements/buttons.scss
  scss/form/inputs.scss
  scss/form/selects.scss
  scss/helpers/_index.scss
  scss/helpers/pointer.scss
  scss/nes-core.scss
  story/select.stories.js
Labels: release

#347 Update the document v2.2.0
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
  docs/index.html
  docs/script.js
Labels: documentation

#348 Release v2.2.0 (Take2)
  .github/README-es.md
  .github/README-jp.md
  .github/README-pt-BR.md
  .github/README-zh-CN.md
  README.md
  docs/index.html
  docs/script.js
Labels: release

#349 Fix transparency of the icons
  scss/icons/instagram.scss
  scss/icons/twitter.scss
  scss/pixel-arts/ash.scss
Labels: enhancement
